# Generated by Django 4.0.3 on 2022-04-15 11:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaypalPaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paypalOrderID', models.CharField(max_length=128)),
                ('paypalPayerID', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='StripePaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripe_id', models.CharField(max_length=120)),
                ('brand', models.CharField(blank=True, max_length=120, null=True)),
                ('country', models.CharField(blank=True, max_length=20, null=True)),
                ('exp_month', models.IntegerField(blank=True, null=True)),
                ('exp_year', models.IntegerField(blank=True, null=True)),
                ('last4', models.CharField(blank=True, max_length=4, null=True)),
                ('default', models.BooleanField(default=True)),
                ('active', models.BooleanField(default=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='payment',
            name='paypalOrderID',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='paypalPayerID',
        ),
        migrations.AlterField(
            model_name='payment',
            name='paymentMethod',
            field=models.CharField(choices=[('None', 'None'), ('Cash', 'Cash'), ('Cheque', 'Cheque'), ('BACS', 'BACS'), ('Paypal', 'Paypal'), ('Stripe', 'Stripe')], default='None', max_length=12),
        ),
        migrations.AddField(
            model_name='payment',
            name='paypal_payment_method',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='payment.paypalpaymentmethod'),
        ),
        migrations.AddField(
            model_name='payment',
            name='stripe_payment_method',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='payment.stripepaymentmethod'),
        ),
    ]
