# Generated by Django 4.0.3 on 2022-04-18 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_paypalpaymentmethod_stripepaymentmethod_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='paypal_payment_method',
            new_name='paypal_forign_key',
        ),
        migrations.RenameField(
            model_name='payment',
            old_name='stripe_payment_method',
            new_name='stripe_forign_key',
        ),
    ]
