# Generated by Django 3.1.12 on 2021-09-11 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_auto_20201129_1337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='total',
            field=models.FloatField(default=0.0),
        ),
    ]
