# Generated by Django 2.2.12 on 2020-06-12 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0003_remove_cart_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='cartItem',
        ),
        migrations.AddField(
            model_name='cart',
            name='cartItem',
            field=models.ManyToManyField(blank=True, default=None, to='carts.CartItem'),
        ),
    ]
