# Generated by Django 2.2.12 on 2020-06-29 13:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20200613_1821'),
        ('carts', '0004_auto_20200612_1533'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='cartItem',
        ),
        migrations.AddField(
            model_name='cart',
            name='product',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='products.Product'),
        ),
    ]
