# Generated by Django 2.2.12 on 2020-06-30 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0007_auto_20200629_1306'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='product',
        ),
        migrations.AddField(
            model_name='cart',
            name='cartItem',
            field=models.ManyToManyField(blank=True, default=None, to='carts.CartItem'),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='price_of_item',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='total',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
