# Generated by Django 2.2.12 on 2020-07-02 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0009_cart_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='cartItem',
            new_name='cart_item',
        ),
    ]
