# Generated by Django 2.2.12 on 2020-07-02 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0010_auto_20200702_2040'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='cart_item',
            new_name='cart_items',
        ),
    ]
