# Generated by Django 2.2.12 on 2020-07-04 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0013_cartitem_session_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='session_id',
            field=models.CharField(blank=True, default=0, max_length=120, null=True),
        ),
    ]
