# Generated by Django 2.2.14 on 2020-10-14 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0023_auto_20201014_0006'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='vat_total',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
