# Generated by Django 3.1.12 on 2021-09-11 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0024_cart_vat_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='subtotal',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='cart',
            name='total',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='cart',
            name='vat_total',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='price_of_item',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='total',
            field=models.FloatField(default=0.0),
        ),
    ]
