# Generated by Django 3.2.9 on 2021-12-09 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0025_auto_20210911_1122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
