# Generated by Django 3.2.11 on 2022-02-05 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0004_auto_20201014_0008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marketingpreference',
            name='mailchimp_subscribed',
            field=models.BooleanField(default=True),
        ),
    ]
