# Generated by Django 2.2.14 on 2020-12-29 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_emailactivation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='full_name',
            field=models.CharField(default=' ', max_length=255),
        ),
    ]
