# Generated by Django 3.2.9 on 2021-12-09 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20211209_1739'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='access_level',
            new_name='group',
        ),
    ]
