# Generated by Django 4.0.3 on 2022-04-03 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_emailactivation_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='group',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
