# Generated by Django 3.2.9 on 2021-12-09 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_rename_access_level_user_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='group',
            field=models.IntegerField(choices=[(0, 'Guest'), (1, 'User'), (2, 'Moderator'), (3, 'Sales'), (4, 'Staff'), (5, 'Admin')], default=0),
        ),
    ]
