# Generated by Django 2.2.14 on 2020-11-28 22:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='text_boy',
            new_name='text_body',
        ),
        migrations.RenameField(
            model_name='blog',
            old_name='subject',
            new_name='title',
        ),
    ]
