# Generated by Django 2.2.14 on 2020-11-28 22:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20201128_2219'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='text_body',
            new_name='blog_post',
        ),
    ]
