# Generated by Django 2.2.12 on 2020-05-31 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
        ('orders', '0003_order_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='product',
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.IntegerField(default=0)),
                ('product', models.ManyToManyField(blank=True, default=None, to='products.Product')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='OrderItem',
            field=models.ManyToManyField(blank=True, default=None, to='orders.OrderItem'),
        ),
    ]
