# Generated by Django 2.2.14 on 2020-07-12 22:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_auto_20200712_2126'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='order_total',
            new_name='total',
        ),
    ]
