# Generated by Django 2.2.14 on 2020-07-27 20:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_delete_invoice'),
        ('orders', '0009_auto_20200712_2207'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='billing_profile',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='billing.BillingProfile'),
        ),
    ]
