# Generated by Django 2.2.14 on 2020-07-27 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_order_billing_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='billing_profile',
        ),
    ]
