# Generated by Django 2.2.14 on 2020-10-31 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0017_productpurchese'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productpurchese',
            name='user',
        ),
        migrations.AddField(
            model_name='productpurchese',
            name='order_id',
            field=models.CharField(default='abc123', max_length=120),
            preserve_default=False,
        ),
    ]
