# Generated by Django 2.2.14 on 2020-10-31 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_product_vat'),
        ('billing', '0008_auto_20201014_0005'),
        ('orders', '0018_auto_20201031_1649'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProductPurchese',
            new_name='ProductPurchase',
        ),
    ]
