# Generated by Django 2.2.14 on 2021-03-05 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ebay', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ebayaccount',
            name='developer_api_key',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
