# Generated by Django 2.2.14 on 2021-03-05 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ebay', '0002_ebayaccount_developer_api_key'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ebayaccount',
            old_name='api_key',
            new_name='production_api_key',
        ),
    ]
