# Generated by Django 2.2.14 on 2021-03-05 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ebay', '0003_auto_20210305_1837'),
    ]

    operations = [
        migrations.AddField(
            model_name='ebayaccount',
            name='oath_token',
            field=models.CharField(blank=True, max_length=256),
        ),
    ]
