# Generated by Django 2.2.14 on 2020-11-03 15:33

import django.core.files.storage
from django.db import migrations, models
import products.models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_productfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productfile',
            name='file',
            field=models.FileField(storage=django.core.files.storage.FileSystemStorage(location='/home/pi/project/Python/development/ecommerce-python3.6v2/static_cdn/protected_media'), upload_to=products.models.upload_product_file_loc),
        ),
    ]
