# Generated by Django 2.2.14 on 2020-11-21 23:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_productfile_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='itemtag',
            old_name='items',
            new_name='product',
        ),
    ]
