# Generated by Django 2.2.14 on 2020-11-21 23:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_auto_20201121_2319'),
    ]

    operations = [
        migrations.RenameField(
            model_name='itemtag',
            old_name='product',
            new_name='products',
        ),
    ]
