# Generated by Django 2.2.14 on 2020-11-25 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_auto_20201121_2319'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, unique=True)),
                ('public', models.BooleanField(default=False)),
                ('blurb', models.CharField(max_length=500, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='ItemTag',
        ),
    ]
