# Generated by Django 2.2.14 on 2020-11-25 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_product_tag'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='tag',
            new_name='tags',
        ),
    ]
